#!/bin/bash

# Joseph Harriott - https://harriott.github.io/ - Thu 11 Apr 2024

# -----------------
# grab key-bindings
# -----------------
# in  $vimfiles/settings/   bash grab.sh

set -e  # terminate on a fail

m(){ echo >> $1; echo 'generated by  $vimfiles/settings/all-unix.sh' >> $1; echo >> $1; }
vfs=$vimfiles/settings

echo 'grab maps of <Fnn>'
# :execute "!grep -ri -E '<(m-|s-)?F[0-9]{1,2}>'"
#  (can't be passed to Bufferize)
of=$vfs/all-unix-map-Fn.txt
echo 'vim: ft=Fn:' > $of; m $of
grep -ri --exclude-dir=settings -E '<(m-|s-)?F[0-9]{1,2}>' ../* >> $of
# rg --no-ignore '<(F|S-F)\d\+>'

echo 'grab maps of <leader>...'
of=$vfs/all-unix-map-leader.txt
echo 'vim: ft=leader:' > $of; m $of
grep -ri --exclude-dir=settings -E '<leader>' ../* >> $of

echo 'Grab maps using <Plug>'
of=$vfs/all-unix-map-Plug.txt
echo 'vim: nowrap:' > $of; m $of
grep -ri --exclude-dir=settings -E '<Plug>' ../* >> $of

