
# Joseph Harriott - https://harriott.github.io/ - Sun 26 Feb 2023

# -----------------
# grab key-bindings
# -----------------
# run this from  $vimfiles/grab/

$vfs = "$vimfiles/settings"

'grab maps of <leader>...'
$of = "$vfs/all-win32-leader.txt"
'vim: ft=leader:' > $of
'' >> $of
'generated by  $vimfiles/settings/all-win32-ps1' >> $of
'' >> $of
pt '<leader>' .. >> $of

