
# Joseph Harriott - https://harriott.github.io/ - Mon 15 Apr 2024

# -----------------
# grab key-bindings
# -----------------
# run this from  $vimfiles/grab/

$vfs = "$vimfiles/settings"

'grab maps of <leader>...'
$of = "$vfs/all-win32.leader"
'' > $of
'generated by  $vimfiles/settings/all-win32-ps1' >> $of
'' >> $of
pt '<leader>' .. >> $of

