#!/bin/bash
# vim set sw=2:

# Joseph Harriott - https://harriott.github.io/ - Thu 03 Apr 2025

# bash $vfs/all-unix-maps.sh

# squash all these into one, as in  $vfs/all-win64.ps1

ml="$vfs/all-unix-maps.rgov"  # $vfv/syntax/rgov.vim
echo > $ml
echo 'generated by  $vfs/all-unix-maps.ps1' >> $ml
echo >> $ml
for vfl in $vimfiles $lazy; do
  echo "rg'ing for maps in  $vfl"
  echo "maps in  $vfl" >> $ml
  echo >> $ml
  rg --field-match-separator=' ⋮' -tlua -tvim --no-ignore -w 'imap|inoremap|keymap|map |nmap|noremap|nnoremap|omap|onoremap|vmap|vnoremap|xmap|xnoremap' $vfl >> $ml
  echo >> $ml
done
