#!/bin/bash
# vim set sw=2:

# Joseph Harriott - https://harriott.github.io/ - Thu 11 Apr 2024

# -----------------
# grab key-bindings
# -----------------
# bash $vimfiles/settings/all-unix.sh

fl(){
  cd $1
  if [[ $1 =~ 'vimfiles' ]]; then
    echo '$vimfiles' >> $2
  else
    echo '$lazy' >> $2
  fi
  echo >> $2
}
ms(){ echo > $1; echo 'generated by  $vimfiles/settings/all-unix.sh' >> $1; echo >> $1; }

echo 'grab maps of <Fnn>'
of="$vimfiles/settings/all-unix-map.Fn"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<(m-|s-)?f[0-9]{1,2}>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

echo 'grab maps of <leader>...'
of="$vimfiles/settings/all-unix-map.leader"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<leader>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

echo 'grab maps using <Plug>'
of="$vimfiles/settings/all-unix-map-Plug.rgo"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<Plug>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

cd $vimfiles/settings/

