#!/bin/bash
# vim set sw=2:

# Joseph Harriott - https://harriott.github.io/ - lun 31 mars 2025

# bash $vfs/all-unix-maps.sh
# squash all these into one, as in  $vfs/all-win64.ps1

fl(){
  cd $1
  if [[ $1 =~ 'vimfiles' ]]; then
    echo '$vimfiles' >> $2
  else
    echo '$lazy' >> $2
  fi
  echo >> $2
}
ms(){ echo > $1; echo 'generated by  $vfs/all-unix.sh' >> $1; echo >> $1; }

echo 'grab maps of <Fnn>'
of="$vfs/all-unix-maps.Fn"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<(m-|s-)?f[0-9]{1,2}>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

echo 'grab maps of <leader>...'
of="$vfs/all-unix-maps.leader"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<leader>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

echo 'grab maps using <Plug>'
of="$vfs/all-unix-maps-Plug.rgo"
ms $of
g(){ fl $1 $of; rg -g='!settings' -i '<Plug>' -uu >> $of; echo >> $of; }
g $vimfiles; g $lazy

cd $vfs/

