
# Joseph Harriott - https://harriott.github.io/ - Fri 25 Apr 2025

# & $vimfiles/settings-maps-all/win64.ps1  # grab all mappings

$ml = "$vimfiles/settings-maps-all/win64.rgov"  # $vfv/syntax/rgov.vim
'' > $ml
'generated by  $vimfiles/settings-maps-all/win64.ps1' >> $ml
'' >> $ml
foreach($vfl in $vimfiles, $lazy){
  "rg'ing for maps in  $vfl"
  "maps in  $vfl" >> $ml
  '' >> $ml
  rg --field-match-separator=' ⋮' -tlua -tvim --no-ignore -w 'imap|inoremap|keymap|map |nmap|noremap|nnoremap|omap|onoremap|vmap|vnoremap|xmap|xnoremap' $vfl >> $ml
  '' >> $ml
  }
sleep 1
((gc $ml) -join "`n") + "`n" | seco -NoNewline $ml  # CRLF -> LF

